export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const SELECT_COUNTRY = "SELECT_COUNTRY";
export const DARK_MODE = "DARK_MODE";
